export default {
  index: 'Overview',
  'gallery-management': 'Gallery Management',
  'gallery-interface': 'Gallery Interface (Guest View)',
  'draft-mode': 'Draft Mode',
  'themes-branding': 'Themes & Branding',
  branding: 'Branding',
  'image-processing': 'Image Processing',
  'email-notifications': 'Email Notifications',
  'photo-protection': 'Photo Protection',
  seo: 'SEO & Robots',
  'external-media': 'External Media',
  analytics: 'Analytics',
  'video-support': 'Video Support',
  feedback: 'Feedback',
  'multi-admin': 'Multi-Admin',
  'customer-accounts': 'Customer Accounts',
  crm: 'CRM',
  'storage-backends': 'Storage Backends (S3)',
  webhooks: 'Webhooks',
  crm: 'CRM (Beta)',
  accounting: 'Accounting (Beta)',
}
