export default {
  index: 'Overview',
  'gallery-management': 'Gallery Management',
  'gallery-interface': 'Gallery Interface (Guest View)',
  'photo-categories': 'Photo Categories & Folders',
  'reveal-mode': 'Reveal Mode & Download Sizes',
  pictransfer: 'PicTransfer',
  'live-slideshow': 'Live Slideshow',
  'draft-mode': 'Draft Mode',
  'themes-branding': 'Themes & Branding',
  branding: 'Branding',
  'image-processing': 'Image Processing',
  'email-notifications': 'Email Notifications',
  'photo-protection': 'Photo Protection',
  seo: 'SEO & Robots',
  'external-media': 'External Media',
  analytics: 'Analytics',
  'video-support': 'Video Support',
  'face-recognition': 'People in Galleries',
  feedback: 'Feedback',
  'multi-admin': 'Multi-Admin',
  'admin-sso': 'Admin SSO (OIDC)',
  'customer-accounts': 'Customer Accounts',
  crm: 'CRM',
  'storage-backends': 'Storage Backends (S3)',
  webhooks: 'Webhooks',
  crm: 'CRM (Beta)',
  accounting: 'Accounting (Beta)',
}
